def assessment_agent(incidents):
    """
    Assessment Agent

    Reads emergency incidents and prepares
    structured information for the planning agent.
    """

    assessed_incidents = []

    for incident in incidents:

        assessed_incidents.append({
            "incident_id": incident["id"],
            "type": incident["type"],
            "location": incident["location"],
            "severity": incident["severity"],
            "required_resources": incident["required_resources"],
            "status": incident["status"]
        })

    return {
        "agent": "Assessment Agent",
        "status": "Completed",
        "incidents_assessed": len(assessed_incidents),
        "data": assessed_incidents
    }


def planning_agent(plan):
    """
    Planning Agent

    Receives the deterministic resource allocation
    generated by planner.py.
    """

    assigned = 0
    attention_required = 0

    for assignment in plan:

        if assignment["status"] == "Assigned":
            assigned += 1

        elif assignment["status"] == "Human Attention Required":
            attention_required += 1

    return {
        "agent": "Planning Agent",
        "status": "Completed",
        "assignments": assigned,
        "human_attention_required": attention_required
    }


def security_agent(validation_results):
    """
    Security/SISO Agent

    Checks whether incident validation passed
    before the plan is accepted.
    """

    failed = []

    for result in validation_results:

        if not result["validation"]["valid"]:
            failed.append(result["incident_id"])

    if failed:

        return {
            "agent": "Security/SISO Agent",
            "status": "Warning",
            "message": "Validation failed",
            "failed_incidents": failed
        }

    return {
        "agent": "Security/SISO Agent",
        "status": "Passed",
        "message": "All incident validation checks passed",
        "failed_incidents": []
    }


def monitoring_agent(changes):
    """
    Monitoring Agent

    Detects whether the current emergency situation
    requires attention or re-planning.
    """

    if changes:

        return {
            "agent": "Monitoring Agent",
            "status": "Change Detected",
            "changes_detected": len(changes),
            "action": "Re-plan required"
        }

    return {
        "agent": "Monitoring Agent",
        "status": "Monitoring",
        "changes_detected": 0,
        "action": "No action required"
    }


def replanning_agent(reason):
    """
    Re-planning Agent

    Decides whether a new response plan should
    be generated after a situation change.
    """

    return {
        "agent": "Re-planning Agent",
        "status": "Triggered",
        "reason": reason,
        "action": "Generate new response plan"
    }